// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyButvhlda5OF2Ablj_43QEfyG8Gn6zS72I',
    appId: '1:725898610839:web:de0fe7ccaccaa24c5601d2',
    messagingSenderId: '725898610839',
    projectId: 'courtu-44f73',
    authDomain: 'courtu-44f73.firebaseapp.com',
    storageBucket: 'courtu-44f73.firebasestorage.app',
    measurementId: 'G-VKDT2PJPHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNI0xuE3xcesPmvYe7IbEpVmeu_jtF-NI',
    appId: '1:725898610839:android:5320f01778a94e185601d2',
    messagingSenderId: '725898610839',
    projectId: 'courtu-44f73',
    storageBucket: 'courtu-44f73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8w-JeyqmVgBEkXk6YYiz2intI_ZQUwU',
    appId: '1:725898610839:ios:28c07d61088e3bf55601d2',
    messagingSenderId: '725898610839',
    projectId: 'courtu-44f73',
    storageBucket: 'courtu-44f73.firebasestorage.app',
    iosBundleId: 'com.example.courtu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi8w-JeyqmVgBEkXk6YYiz2intI_ZQUwU',
    appId: '1:725898610839:ios:28c07d61088e3bf55601d2',
    messagingSenderId: '725898610839',
    projectId: 'courtu-44f73',
    storageBucket: 'courtu-44f73.firebasestorage.app',
    iosBundleId: 'com.example.courtu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyButvhlda5OF2Ablj_43QEfyG8Gn6zS72I',
    appId: '1:725898610839:web:2107bf29ba1c581d5601d2',
    messagingSenderId: '725898610839',
    projectId: 'courtu-44f73',
    authDomain: 'courtu-44f73.firebaseapp.com',
    storageBucket: 'courtu-44f73.firebasestorage.app',
    measurementId: 'G-60CJ2LJVY1',
  );
}
